[package]
name = "annie-mai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dotenv = "0.15"
env_logger = "0.9"
futures = "0.3.21"
html2md = "0.2.13"
log = "0.4"
ngrammatic = "0.3.5"
reqwest = { version = "0.11.10", features = ["blocking"] }
serde = "1.0"
serde_json = "1.0"
serenity = { version = "0.11", features = ["framework", "standard_framework"] }
titlecase = "1.1.0"
tokio = { version = "1.17", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
