[package]
name = "annie-mai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.16"
serenity = { version = "0.10.10", features = [
  "framework",
  "standard_framework",
] }
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.33"
tracing-subscriber = "0.3.11"
