name: build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/cargo@v1
    - name: Build for Rasperry PI
      with:
        use-cross: true
        command: build
        args: --target armv7-unknown-linux-gnueabihf
