name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        rustup target add armv7-unknown-linux-gnueabihf
        cargo build --verbose --release --target=armv7-unknown-linux-gnueabihf
