on: [push]

name: ARMv7 build

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
    - name: Build-checkout
      uses: actions/checkout@v3
    - name: Build-toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: armv7-unknown-linux-gnueabihf
        override: true
    - name: Build-cargo-cross
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target armv7-unknown-linux-gnueabihf --release
    - name: Check dir 
      run: ls target
    - name: Release
      uses: actions/upload-artifact@v3
      with:
        name: anni-mai-armv7
        path: target/release
